---
# Install and start Docker on ec2 linux server
- name: Install Docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start Docker deamon
      systemd:
        name: docker
        state: started
# Fetch and install Docker-compose
- name: Install Docker-compose
  hosts: docker_server
  tasks:
    - name: Create Docker-compose dir
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64
        dest: /home/ec2-user/.docker/cli-plugins/docker-compose
        mode: +x
# Add ec2-user to docker group
- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Recconect to server session
      meta: reset_connection
# Copy docker-compose file to ec2 instance and start docker contaners
- name: Start docker container
  hosts: docker_server
  become: yes
  become_user: ec2-user
  vars_files:
    - project-vars

  tasks:
    - name: Copy docker compose
      copy:
        src: /Users/tsemb/m15-Ansible/deploy-docker-ec2/docker-compose-full.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login:
        username: tsemb
        password: "{{ docker_password }}"
    - name: Start containers from compose
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user