---
- name: Install node and npm
  hosts: webserver
  vars:
    linux_name: ansible-user
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: webserver
  vars:
    linux_name: ansible-user
  tasks:
    - name: Create linux user
      user:
        name: "{{ linux_name }}"
        comment: Node User
        group: admin

- name: Deploy nodejs app
  hosts: webserver
  become: true
  become_user: "{{ linux_name }}"
  vars:
    linux_name: ansible-user
    location: /Users/tsemb/m15-Ansible/nodejs-app
    version: 1.0.0
    user_home_dir: "/home/{{ linux_name }}"
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: "{{ location }}/nodejs-app-{{ version }}.tgz"
        dest: "{{ user_home_dir }}"

    - name: Install dependencies
      npm:
        path: "{{ user_home_dir }}/package"

    - name: Start the application
      command:
        chdir: "{{ user_home_dir }}/package/app"
        cmd: node server
      async: 1000
      poll: 0

    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status

    - name: Display app status
      debug:
        msg: "{{ app_status.stdout_lines }}"
